#!/usr/bin/zsh

# A small hack to get pyvenv working on Ubuntu 14.04 trusty
# (https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1290847)

if [ "$#" -ne 1 ]; then
    echo "Usage: pyvenv VENV_NAME"
    exit 1
fi

pyvenv-3.4 --without-pip $1
source $1/bin/activate
curl -s https://bootstrap.pypa.io/get-pip.py | python3
deactivate
